name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
  
  test:
    name: Complex test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build test version
      run: make build_test
    - name: testing
      run: ./oneCC-test && exit 0 || exit 1